In [1]:
print("EconoCausal setup successful!")

EconoCausal setup successful!

In [2]:
%pip install numpy pandas scipy scikit-learn matplotlib seaborn

Requirement already satisfied: numpy in c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages (2.4.6)
Collecting pandas
  Downloading pandas-3.0.6-cp311-cp311-win_amd64.whl.metadata (19 kB)
Collecting scipy
  Downloading scipy-1.17.1-cp311-cp311-win_amd64.whl.metadata (60 kB)
Collecting scikit-learn
  Downloading scikit_learn-1.9.1-cp311-cp311-win_amd64.whl.metadata (9.3 kB)
Requirement already satisfied: matplotlib in c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages (3.11.1)
Collecting seaborn
  Downloading seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Downloading tzdata-2026.5-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting joblib>=1.4.0 (from scikit-learn)
  Downloading joblib-1.6.0-py3-none-any.whl.metadata (6.5 kB)
Collecting narwhals>=2.0.1 (from scikit-learn)
  Downloading narwhals-2.27.1-py3-none-any.whl.metadata (15 kB)
Collecting threadpoolctl>=3.5.0 (from scikit-learn)
  Downloading threadpoolctl-3.7.0-py3-none-any.whl.metadata (24 kB)
Requirement already satisfied: contourpy>=1.0.1 in c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages (from matplotlib) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: packaging>=20.0 in c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages (from matplotlib) (26.3)
Requirement already satisfied: pillow>=9 in c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages (from matplotlib) (12.3.0)
Requirement already satisfied: pyparsing>=3 in c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages (from matplotlib) (3.3.2)
Collecting cloudpickle>=3.0 (from joblib>=1.4.0->scikit-learn)
  Downloading cloudpickle-3.1.2-py3-none-any.whl.metadata (7.1 kB)
Requirement already satisfied: six>=1.5 in c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.6-cp311-cp311-win_amd64.whl (9.9 MB)
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---- ----------------------------------- 1.0/9.9 MB 7.2 MB/s eta 0:00:02
   ---------- ----------------------------- 2.6/9.9 MB 7.6 MB/s eta 0:00:01
   ------------------ --------------------- 4.5/9.9 MB 7.9 MB/s eta 0:00:01
   ------------------------- -------------- 6.3/9.9 MB 8.0 MB/s eta 0:00:01
   ---------------------------- ----------- 7.1/9.9 MB 7.5 MB/s eta 0:00:01
   ----------------------------------- ---- 8.7/9.9 MB 7.3 MB/s eta 0:00:01
   ---------------------------------------- 9.9/9.9 MB 7.0 MB/s  0:00:01
Downloading scipy-1.17.1-cp311-cp311-win_amd64.whl (36.6 MB)
   ---------------------------------------- 0.0/36.6 MB ? eta -:--:--
   - -------------------------------------- 1.6/36.6 MB 7.6 MB/s eta 0:00:05
   --- ------------------------------------ 3.4/36.6 MB 8.8 MB/s eta 0:00:04
   ----- ---------------------------------- 5.2/36.6 MB 8.9 MB/s eta 0:00:04
   ------- -------------------------------- 7.1/36.6 MB 8.6 MB/s eta 0:00:04
   --------- ------------------------------ 8.7/36.6 MB 8.5 MB/s eta 0:00:04
   ----------- ---------------------------- 10.5/36.6 MB 8.6 MB/s eta 0:00:04
   ------------- -------------------------- 12.1/36.6 MB 8.5 MB/s eta 0:00:03
   --------------- ------------------------ 14.2/36.6 MB 8.5 MB/s eta 0:00:03
   ----------------- ---------------------- 16.3/36.6 MB 8.7 MB/s eta 0:00:03
   ------------------- -------------------- 17.8/36.6 MB 8.5 MB/s eta 0:00:03
   --------------------- ------------------ 19.7/36.6 MB 8.6 MB/s eta 0:00:02
   ----------------------- ---------------- 21.5/36.6 MB 8.6 MB/s eta 0:00:02
   ------------------------- -------------- 23.6/36.6 MB 8.6 MB/s eta 0:00:02
   ---------------------------- ----------- 25.7/36.6 MB 8.8 MB/s eta 0:00:02
   ------------------------------ --------- 27.5/36.6 MB 8.7 MB/s eta 0:00:02
   -------------------------------- ------- 29.4/36.6 MB 8.7 MB/s eta 0:00:01
   ---------------------------------- ----- 31.5/36.6 MB 8.8 MB/s eta 0:00:01
   ------------------------------------ --- 33.8/36.6 MB 8.9 MB/s eta 0:00:01
   ---------------------------------------  35.9/36.6 MB 8.9 MB/s eta 0:00:01
   ---------------------------------------  36.4/36.6 MB 9.0 MB/s eta 0:00:01
   ---------------------------------------- 36.6/36.6 MB 8.6 MB/s  0:00:04
Downloading scikit_learn-1.9.1-cp311-cp311-win_amd64.whl (8.3 MB)
   ---------------------------------------- 0.0/8.3 MB ? eta -:--:--
   ----------- ---------------------------- 2.4/8.3 MB 12.2 MB/s eta 0:00:01
   ------------------ --------------------- 3.9/8.3 MB 9.8 MB/s eta 0:00:01
   ---------------------------- ----------- 6.0/8.3 MB 10.0 MB/s eta 0:00:01
   ---------------------------------------  8.1/8.3 MB 9.9 MB/s eta 0:00:01
   ---------------------------------------- 8.3/8.3 MB 9.2 MB/s  0:00:00
Downloading seaborn-0.13.2-py3-none-any.whl (294 kB)
Downloading joblib-1.6.0-py3-none-any.whl (306 kB)
Downloading cloudpickle-3.1.2-py3-none-any.whl (22 kB)
Downloading narwhals-2.27.1-py3-none-any.whl (483 kB)
Downloading threadpoolctl-3.7.0-py3-none-any.whl (26 kB)
Downloading tzdata-2026.5-py2.py3-none-any.whl (347 kB)
Installing collected packages: tzdata, threadpoolctl, scipy, narwhals, cloudpickle, pandas, joblib, seaborn, scikit-learn

   ---------------------------------------- 0/9 [tzdata]
   ---------------------------------------- 0/9 [tzdata]
   ---------------------------------------- 0/9 [tzdata]
   ---------------------------------------- 0/9 [tzdata]
   ---------------------------------------- 0/9 [tzdata]
   ---------------------------------------- 0/9 [tzdata]
   ---------------------------------------- 0/9 [tzdata]
   ---- ----------------------------------- 1/9 [threadpoolctl]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   -------- ------------------------------- 2/9 [scipy]
   ------------- -------------------------- 3/9 [narwhals]
   ------------- -------------------------- 3/9 [narwhals]
   ------------- -------------------------- 3/9 [narwhals]
   ------------- -------------------------- 3/9 [narwhals]
   ------------- -------------------------- 3/9 [narwhals]
   ------------- -------------------------- 3/9 [narwhals]
   ------------- -------------------------- 3/9 [narwhals]
   ------------- -------------------------- 3/9 [narwhals]
   ------------- -------------------------- 3/9 [narwhals]
   ------------- -------------------------- 3/9 [narwhals]
   ------------- -------------------------- 3/9 [narwhals]
   ------------- -------------------------- 3/9 [narwhals]
   ------------- -------------------------- 3/9 [narwhals]
   ------------- -------------------------- 3/9 [narwhals]
   ------------- -------------------------- 3/9 [narwhals]
   ------------- -------------------------- 3/9 [narwhals]
   ------------- -------------------------- 3/9 [narwhals]
   ------------- -------------------------- 3/9 [narwhals]
   ------------- -------------------------- 3/9 [narwhals]
   ------------- -------------------------- 3/9 [narwhals]
   ------------- -------------------------- 3/9 [narwhals]
   ------------- -------------------------- 3/9 [narwhals]
   ------------- -------------------------- 3/9 [narwhals]
   ------------- -------------------------- 3/9 [narwhals]
   ------------- -------------------------- 3/9 [narwhals]
   ------------- -------------------------- 3/9 [narwhals]
   ------------- -------------------------- 3/9 [narwhals]
   ------------- -------------------------- 3/9 [narwhals]
   ------------- -------------------------- 3/9 [narwhals]
   ------------- -------------------------- 3/9 [narwhals]
   ------------- -------------------------- 3/9 [narwhals]
   ------------- -------------------------- 3/9 [narwhals]
   ------------- -------------------------- 3/9 [narwhals]
   ------------- -------------------------- 3/9 [narwhals]
   ------------- -------------------------- 3/9 [narwhals]
   ------------- -------------------------- 3/9 [narwhals]
   ------------- -------------------------- 3/9 [narwhals]
   ------------- -------------------------- 3/9 [narwhals]
   ------------- -------------------------- 3/9 [narwhals]
   ------------- -------------------------- 3/9 [narwhals]
   ----------------- ---------------------- 4/9 [cloudpickle]

In [3]:
import numpy as np
import pandas as pd
import scipy
import sklearn
import matplotlib
import seaborn

print("NumPy:", np.__version__)
print("Pandas:", pd.__version__)
print("SciPy:", scipy.__version__)
print("Scikit-learn:", sklearn.__version__)
print("All basic packages are working!")

NumPy: 2.4.6
Pandas: 3.0.6
SciPy: 1.17.1
Scikit-learn: 1.9.1
All basic packages are working!

In [4]:
import numpy as np
import pandas as pd

N = 100_000

df = pd.DataFrame({
    "customer_id": [f"C{i:06d}" for i in range(1, N + 1)]
})

df.head()

  customer_id
0     C000001
1     C000002
2     C000003
3     C000004
4     C000005

In [5]:
print("Number of customers:", len(df))

Number of customers: 100000

In [6]:
df.tail()

      customer_id
99995     C099996
99996     C099997
99997     C099998
99998     C099999
99999     C100000

In [7]:
df["age"] = np.random.randint(18, 71, size=N)

df[["customer_id", "age"]].head()

  customer_id  age
0     C000001   26
1     C000002   57
2     C000003   62
3     C000004   47
4     C000005   65

In [8]:
print("Minimum age:", df["age"].min())
print("Maximum age:", df["age"].max())

Minimum age: 18
Maximum age: 70

In [9]:
df["past_purchases"] = np.random.poisson(
    lam=3,
    size=N
)

# Keep the value between 0 and 15
df["past_purchases"] = df["past_purchases"].clip(0, 15)

df[["customer_id", "age", "past_purchases"]].head()

  customer_id  age  past_purchases
0     C000001   26               0
1     C000002   57               2
2     C000003   62               4
3     C000004   47               3
4     C000005   65               3

In [10]:
print("Minimum:", df["past_purchases"].min())
print("Maximum:", df["past_purchases"].max())
print("Average:", round(df["past_purchases"].mean(), 2))

Minimum: 0
Maximum: 15
Average: 3.01

In [12]:
df["website_visits"] = np.random.poisson(
    lam=8,
    size=N
)

df["website_visits"] = df["website_visits"].clip(0, 40)

In [13]:
df["product_views"] = np.random.poisson(
    lam=12,
    size=N
)

df["product_views"] = df["product_views"].clip(0, 60)

df[["customer_id", "website_visits", "product_views"]].head()

  customer_id  website_visits  product_views
0     C000001               7              4
1     C000002              14             13
2     C000003               8             10
3     C000004               9              8
4     C000005              10             12

In [14]:
df["avg_order_value"] = np.random.normal(
    loc=1500,
    scale=500,
    size=N
).round(2)

df["avg_order_value"] = df["avg_order_value"].clip(200, 5000)

df[["customer_id", "past_purchases", "avg_order_value"]].head()

  customer_id  past_purchases  avg_order_value
0     C000001               0          1629.17
1     C000002               2          2006.95
2     C000003               4          2408.13
3     C000004               3          1433.72
4     C000005               3          1935.84

In [15]:
print("Minimum:", df["avg_order_value"].min())
print("Maximum:", df["avg_order_value"].max())
print("Average:", round(df["avg_order_value"].mean(), 2))

Minimum: 200.0
Maximum: 3567.36
Average: 1500.94

In [16]:
df["days_since_last_purchase"] = np.random.randint(
    1, 181,
    size=N
)

df[["customer_id", "past_purchases", "days_since_last_purchase"]].head()

  customer_id  past_purchases  days_since_last_purchase
0     C000001               0                        34
1     C000002               2                        44
2     C000003               4                       120
3     C000004               3                       134
4     C000005               3                       134

In [17]:
print("Minimum:", df["days_since_last_purchase"].min())
print("Maximum:", df["days_since_last_purchase"].max())
print("Average:", round(df["days_since_last_purchase"].mean(), 2))

Minimum: 1
Maximum: 180
Average: 90.81

In [18]:
df["loyalty_score"] = np.random.randint(
    1, 101,
    size=N
)

df[["customer_id", "past_purchases", "loyalty_score"]].head()

  customer_id  past_purchases  loyalty_score
0     C000001               0             69
1     C000002               2              8
2     C000003               4             67
3     C000004               3             20
4     C000005               3             55

In [19]:
print("Minimum:", df["loyalty_score"].min())
print("Maximum:", df["loyalty_score"].max())
print("Average:", round(df["loyalty_score"].mean(), 2))

Minimum: 1
Maximum: 100
Average: 50.58

In [20]:
df["cart_additions"] = np.random.poisson(
    lam=3,
    size=N
)

df["cart_additions"] = df["cart_additions"].clip(0, 20)

df[["customer_id", "product_views", "cart_additions"]].head()

  customer_id  product_views  cart_additions
0     C000001              4               7
1     C000002             13               3
2     C000003             10               3
3     C000004              8               4
4     C000005             12               3

In [21]:
print("Minimum:", df["cart_additions"].min())
print("Maximum:", df["cart_additions"].max())
print("Average:", round(df["cart_additions"].mean(), 2))

Minimum: 0
Maximum: 13
Average: 3.0

In [22]:
df["email_engagement"] = np.random.randint(
    0, 101,
    size=N
)

df[["customer_id", "email_engagement"]].head()

  customer_id  email_engagement
0     C000001                25
1     C000002                31
2     C000003                80
3     C000004                31
4     C000005                 3

In [23]:
print("Minimum:", df["email_engagement"].min())
print("Maximum:", df["email_engagement"].max())
print("Average:", round(df["email_engagement"].mean(), 2))

Minimum: 0
Maximum: 100
Average: 49.98

In [24]:
df["customer_tenure"] = np.random.randint(
    1, 61,
    size=N
)

df[["customer_id", "customer_tenure"]].head()

  customer_id  customer_tenure
0     C000001               21
1     C000002               51
2     C000003               51
3     C000004                9
4     C000005               53

In [25]:
print("Minimum:", df["customer_tenure"].min())
print("Maximum:", df["customer_tenure"].max())
print("Average:", round(df["customer_tenure"].mean(), 2))

Minimum: 1
Maximum: 60
Average: 30.46

In [26]:
df["product_interest_score"] = np.random.randint(
    1, 101,
    size=N
)

df[["customer_id", "product_views", "cart_additions", "product_interest_score"]].head()

  customer_id  product_views  cart_additions  product_interest_score
0     C000001              4               7                      60
1     C000002             13               3                      87
2     C000003             10               3                      44
3     C000004              8               4                      87
4     C000005             12               3                      78

In [27]:
print("Minimum:", df["product_interest_score"].min())
print("Maximum:", df["product_interest_score"].max())
print("Average:", round(df["product_interest_score"].mean(), 2))

Minimum: 1
Maximum: 100
Average: 50.62

In [28]:
df["previous_discount_usage"] = np.random.poisson(
    lam=2,
    size=N
)

df["previous_discount_usage"] = df["previous_discount_usage"].clip(0, 10)

df[["customer_id", "past_purchases", "previous_discount_usage"]].head()

  customer_id  past_purchases  previous_discount_usage
0     C000001               0                        1
1     C000002               2                        3
2     C000003               4                        0
3     C000004               3                        1
4     C000005               3                        4

In [29]:
print("Minimum:", df["previous_discount_usage"].min())
print("Maximum:", df["previous_discount_usage"].max())
print("Average:", round(df["previous_discount_usage"].mean(), 2))

Minimum: 0
Maximum: 10
Average: 2.0

In [30]:
df["discount"] = np.random.choice(
    [0, 10, 20],
    size=N,
    p=[0.4, 0.3, 0.3]
)

df[["customer_id", "discount"]].head()

  customer_id  discount
0     C000001         0
1     C000002        20
2     C000003        20
3     C000004         0
4     C000005         0

In [31]:
print(df["discount"].value_counts().sort_index())

discount
0     39856
10    30138
20    30006
Name: count, dtype: int64

In [32]:
baseline_score = (
    -3
    + 0.08 * df["loyalty_score"]
    + 0.10 * df["product_interest_score"]
    + 0.12 * df["past_purchases"]
    + 0.04 * df["website_visits"]
    + 0.03 * df["cart_additions"]
    - 0.008 * df["days_since_last_purchase"]
)

In [34]:
baseline_probability = 1 / (1 + np.exp(-baseline_score))

In [35]:
baseline_probability.head()

0    0.999840
1    0.998971
2    0.998758
3    0.999149
4    0.999874
dtype: float64

In [36]:
treatment_effect = (
    0.002 * df["product_interest_score"]
    + 0.001 * df["loyalty_score"]
    + 0.003 * df["cart_additions"]
)

In [37]:
discount_effect = (
    treatment_effect * (df["discount"] / 10)
)

In [38]:
purchase_probability = baseline_probability + discount_effect

In [39]:
purchase_probability = purchase_probability.clip(0.01, 0.99)

In [40]:
print(purchase_probability.describe())

count    100000.000000
mean          0.934792
std           0.161123
min           0.032909
25%           0.990000
50%           0.990000
75%           0.990000
max           0.990000
dtype: float64

In [41]:
df["purchase"] = np.random.binomial(
    1,
    purchase_probability,
    size=N
)

df[["customer_id", "discount", "purchase"]].head()

  customer_id  discount  purchase
0     C000001         0         1
1     C000002        20         1
2     C000003        20         1
3     C000004         0         1
4     C000005         0         1

In [42]:
print("Overall purchase rate:", round(df["purchase"].mean() * 100, 2), "%")

Overall purchase rate: 93.34 %

In [43]:
print(
    df.groupby("discount")["purchase"]
      .mean()
      .mul(100)
      .round(2)
)

discount
0     92.23
10    93.60
20    94.55
Name: purchase, dtype: float64

In [44]:
print(df.shape)
print(df.columns.tolist())

(100000, 15)
['customer_id', 'age', 'past_purchases', 'product_views', 'website_visits', 'avg_order_value', 'days_since_last_purchase', 'loyalty_score', 'cart_additions', 'email_engagement', 'customer_tenure', 'product_interest_score', 'previous_discount_usage', 'discount', 'purchase']

In [45]:
df.head()

,customer_id,age,past_purchases,product_views,website_visits,avg_order_value,days_since_last_purchase,loyalty_score,cart_additions,email_engagement,customer_tenure,product_interest_score,previous_discount_usage,discount,purchase
0,C000001,26,0,4,7,1629.17,34,69,7,25,21,60,1,0,1
1,C000002,57,2,13,14,2006.95,44,8,3,31,51,87,3,20,1
2,C000003,62,4,10,8,2408.13,120,67,3,80,51,44,0,20,1
3,C000004,47,3,8,9,1433.72,134,20,4,31,9,87,1,0,1
4,C000005,65,3,12,10,1935.84,134,55,3,3,53,78,4,0,1

In [46]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 15 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   customer_id               100000 non-null  str
 1   age                       100000 non-null  int32
 2   past_purchases            100000 non-null  int32
 3   product_views             100000 non-null  int32
 4   website_visits            100000 non-null  int32
 5   avg_order_value           100000 non-null  float64
 6   days_since_last_purchase  100000 non-null  int32
 7   loyalty_score             100000 non-null  int32
 8   cart_additions            100000 non-null  int32
 9   email_engagement          100000 non-null  int32
 10  customer_tenure           100000 non-null  int32
 11  product_interest_score    100000 non-null  int32
 12  previous_discount_usage   100000 non-null  int32
 13  discount                  100000 non-null  int64
 14  purchase                  100000 non-null  int32
dtypes: float64(1), int32(12), int64(1), str(1)
memory usage: 6.9 MB

In [47]:
df["customer_id"].duplicated().sum()

np.int64(0)

In [48]:
df.isnull().sum()

customer_id                 0
age                         0
past_purchases              0
product_views               0
website_visits              0
avg_order_value             0
days_since_last_purchase    0
loyalty_score               0
cart_additions              0
email_engagement            0
customer_tenure             0
product_interest_score      0
previous_discount_usage     0
discount                    0
purchase                    0
dtype: int64

In [49]:
df.describe()

,age,past_purchases,product_views,website_visits,avg_order_value,days_since_last_purchase,loyalty_score,cart_additions,email_engagement,customer_tenure,product_interest_score,previous_discount_usage,discount,purchase
count,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000
mean,43.962950,3.007870,11.993910,8.002290,1500.935179,90.814780,50.578470,3.002870,49.980180,30.459330,50.621100,2.004900,9.015000,0.933370
std,15.317476,1.733043,3.457504,2.833469,497.716873,51.975693,28.837263,1.734068,29.096093,17.282523,28.898353,1.414467,8.300148,0.249381
min,18.000000,0.000000,1.000000,0.000000,200.000000,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000
25%,31.000000,2.000000,10.000000,6.000000,1162.510000,46.000000,26.000000,2.000000,25.000000,15.000000,26.000000,1.000000,0.000000,1.000000
50%,44.000000,3.000000,12.000000,8.000000,1500.720000,91.000000,50.000000,3.000000,50.000000,30.000000,51.000000,2.000000,10.000000,1.000000
75%,57.000000,4.000000,14.000000,10.000000,1838.680000,136.000000,76.000000,4.000000,75.000000,45.000000,76.000000,3.000000,20.000000,1.000000
max,70.000000,15.000000,28.000000,24.000000,3567.360000,180.000000,100.000000,13.000000,100.000000,60.000000,100.000000,10.000000,20.000000,1.000000

In [50]:
df.groupby("discount")["purchase"].mean().mul(100).round(2)

discount
0     92.23
10    93.60
20    94.55
Name: purchase, dtype: float64

In [51]:
baseline_score = (
    -5
    + 0.04 * df["loyalty_score"]
    + 0.05 * df["product_interest_score"]
    + 0.08 * df["past_purchases"]
    + 0.02 * df["website_visits"]
    + 0.02 * df["cart_additions"]
    - 0.005 * df["days_since_last_purchase"]
)

In [52]:
baseline_probability = 1 / (1 + np.exp(-baseline_score))

In [53]:
treatment_effect = (
    0.002 * df["product_interest_score"]
    + 0.001 * df["loyalty_score"]
    + 0.003 * df["cart_additions"]
)

In [54]:
discount_effect = (
    treatment_effect * (df["discount"] / 10)
)

In [55]:
purchase_probability = baseline_probability + discount_effect

In [56]:
purchase_probability = purchase_probability.clip(0.01, 0.99)

In [57]:
print("Average purchase probability:",
      round(purchase_probability.mean() * 100, 2), "%")

Average purchase probability: 54.19 %

In [58]:
df["purchase"] = np.random.binomial(
    1,
    purchase_probability,
    size=N
)

In [59]:
print(
    df.groupby("discount")["purchase"]
      .mean()
      .mul(100)
      .round(2)
)

discount
0     43.39
10    56.96
20    66.01
Name: purchase, dtype: float64

In [60]:
df.to_csv("../data/raw_customer_data.csv", index=False)

In [61]:
print("Dataset saved successfully!")

Dataset saved successfully!

In [1]:
import pandas as pd

df = pd.read_csv("../data/raw_customer_data.csv")

df.head()

,customer_id,age,past_purchases,product_views,website_visits,avg_order_value,days_since_last_purchase,loyalty_score,cart_additions,email_engagement,customer_tenure,product_interest_score,previous_discount_usage,discount,purchase
0,C000001,26,0,4,7,1629.17,34,69,7,25,21,60,1,0,1
1,C000002,57,2,13,14,2006.95,44,8,3,31,51,87,3,20,1
2,C000003,62,4,10,8,2408.13,120,67,3,80,51,44,0,20,0
3,C000004,47,3,8,9,1433.72,134,20,4,31,9,87,1,0,0
4,C000005,65,3,12,10,1935.84,134,55,3,3,53,78,4,0,0

In [2]:
df.shape

(100000, 15)

In [3]:
df.isnull().sum()

customer_id                 0
age                         0
past_purchases              0
product_views               0
website_visits              0
avg_order_value             0
days_since_last_purchase    0
loyalty_score               0
cart_additions              0
email_engagement            0
customer_tenure             0
product_interest_score      0
previous_discount_usage     0
discount                    0
purchase                    0
dtype: int64

In [4]:
df["customer_id"].duplicated().sum()

np.int64(0)

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 15 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   customer_id               100000 non-null  str
 1   age                       100000 non-null  int64
 2   past_purchases            100000 non-null  int64
 3   product_views             100000 non-null  int64
 4   website_visits            100000 non-null  int64
 5   avg_order_value           100000 non-null  float64
 6   days_since_last_purchase  100000 non-null  int64
 7   loyalty_score             100000 non-null  int64
 8   cart_additions            100000 non-null  int64
 9   email_engagement          100000 non-null  int64
 10  customer_tenure           100000 non-null  int64
 11  product_interest_score    100000 non-null  int64
 12  previous_discount_usage   100000 non-null  int64
 13  discount                  100000 non-null  int64
 14  purchase                  100000 non-null  int64
dtypes: float64(1), int64(13), str(1)
memory usage: 11.4 MB

In [6]:
df.describe()

,age,past_purchases,product_views,website_visits,avg_order_value,days_since_last_purchase,loyalty_score,cart_additions,email_engagement,customer_tenure,product_interest_score,previous_discount_usage,discount,purchase
count,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.00000
mean,43.962950,3.007870,11.993910,8.002290,1500.935179,90.814780,50.578470,3.002870,49.980180,30.459330,50.621100,2.004900,9.015000,0.54265
std,15.317476,1.733043,3.457504,2.833469,497.716873,51.975693,28.837263,1.734068,29.096093,17.282523,28.898353,1.414467,8.300148,0.49818
min,18.000000,0.000000,1.000000,0.000000,200.000000,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.00000
25%,31.000000,2.000000,10.000000,6.000000,1162.510000,46.000000,26.000000,2.000000,25.000000,15.000000,26.000000,1.000000,0.000000,0.00000
50%,44.000000,3.000000,12.000000,8.000000,1500.720000,91.000000,50.000000,3.000000,50.000000,30.000000,51.000000,2.000000,10.000000,1.00000
75%,57.000000,4.000000,14.000000,10.000000,1838.680000,136.000000,76.000000,4.000000,75.000000,45.000000,76.000000,3.000000,20.000000,1.00000
max,70.000000,15.000000,28.000000,24.000000,3567.360000,180.000000,100.000000,13.000000,100.000000,60.000000,100.000000,10.000000,20.000000,1.00000

In [7]:
df["discount"].value_counts().sort_index()

discount
0     39856
10    30138
20    30006
Name: count, dtype: int64

In [8]:
df.groupby("discount")["purchase"].mean()

discount
0     0.433862
10    0.569580
20    0.660101
Name: purchase, dtype: float64

In [9]:
df.corr(numeric_only=True)

,age,past_purchases,product_views,website_visits,avg_order_value,days_since_last_purchase,loyalty_score,cart_additions,email_engagement,customer_tenure,product_interest_score,previous_discount_usage,discount,purchase
age,1.000000,-0.002927,-0.001669,0.001572,-0.002529,-0.003427,0.004423,0.001679,0.002820,-0.007470,-0.003705,0.003960,0.001191,-0.002920
past_purchases,-0.002927,1.000000,0.008650,0.010075,0.002130,-0.002532,-0.001467,0.000465,-0.003976,-0.006491,-0.003093,0.002338,-0.001818,0.031296
product_views,-0.001669,0.008650,1.000000,-0.002289,-0.000533,0.005613,-0.004009,-0.002397,0.003842,0.000427,-0.006079,0.004687,-0.002464,-0.004084
website_visits,0.001572,0.010075,-0.002289,1.000000,0.002051,0.002620,-0.001953,0.002296,0.003629,-0.002444,0.003451,-0.003488,-0.001380,0.013451
avg_order_value,-0.002529,0.002130,-0.000533,0.002051,1.000000,0.001050,-0.003542,-0.004453,-0.002979,0.000733,-0.000544,0.001056,-0.002044,0.002595
days_since_last_purchase,-0.003427,-0.002532,0.005613,0.002620,0.001050,1.000000,-0.000151,0.000880,-0.004076,-0.000543,-0.000150,0.000516,-0.001311,-0.070506
loyalty_score,0.004423,-0.001467,-0.004009,-0.001953,-0.003542,-0.000151,1.000000,-0.001305,0.002735,0.000361,-0.007171,-0.002108,0.000191,0.346898
cart_additions,0.001679,0.000465,-0.002397,0.002296,-0.004453,0.000880,-0.001305,1.000000,0.001154,-0.001086,0.001534,-0.004507,-0.000790,0.021002
email_engagement,0.002820,-0.003976,0.003842,0.003629,-0.002979,-0.004076,0.002735,0.001154,1.000000,0.001166,-0.000275,-0.000601,0.002027,0.001998
customer_tenure,-0.007470,-0.006491,0.000427,-0.002444,0.000733,-0.000543,0.000361,-0.001086,0.001166,1.000000,0.003068,-0.005626,-0.002621,0.001207
product_interest_score,-0.003705,-0.003093,-0.006079,0.003451,-0.000544,-0.000150,-0.007171,0.001534,-0.000275,0.003068,1.000000,0.006063,-0.005026,0.490834
previous_discount_usage,0.003960,0.002338,0.004687,-0.003488,0.001056,0.000516,-0.002108,-0.004507,-0.000601,-0.005626,0.006063,1.000000,0.001944,0.000739
discount,0.001191,-0.001818,-0.002464,-0.001380,-0.002044,-0.001311,0.000191,-0.000790,0.002027,-0.002621,-0.005026,0.001944,1.000000,0.190090
purchase,-0.002920,0.031296,-0.004084,0.013451,0.002595,-0.070506,0.346898,0.021002,0.001998,0.001207,0.490834,0.000739,0.190090,1.000000

In [10]:
df_clean = df.copy()

df_clean.shape

(100000, 15)

In [11]:
df_clean.duplicated().sum()

np.int64(0)

In [12]:
id="v7c2ma"
print("Age outside 18–70:", ((df_clean["age"] < 18) | (df_clean["age"] > 70)).sum())
print("Negative past purchases:", (df_clean["past_purchases"] < 0).sum())
print("Negative website visits:", (df_clean["website_visits"] < 0).sum())
print("Negative cart additions:", (df_clean["cart_additions"] < 0).sum())
print("Loyalty score outside 1–100:", ((df_clean["loyalty_score"] < 1) | (df_clean["loyalty_score"] > 100)).sum())
print("Interest score outside 1–100:", ((df_clean["product_interest_score"] < 1) | (df_clean["product_interest_score"] > 100)).sum())
print("Invalid discount:", (~df_clean["discount"].isin([0, 10, 20])).sum())
print("Invalid purchase:", (~df_clean["purchase"].isin([0, 1])).sum())

Age outside 18–70: 0
Negative past purchases: 0
Negative website visits: 0
Negative cart additions: 0
Loyalty score outside 1–100: 0
Interest score outside 1–100: 0
Invalid discount: 0
Invalid purchase: 0

In [13]:
Q1 = df_clean["avg_order_value"].quantile(0.25)
Q3 = df_clean["avg_order_value"].quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

outliers = df_clean[
    (df_clean["avg_order_value"] < lower_bound) |
    (df_clean["avg_order_value"] > upper_bound)
]

print("Lower bound:", lower_bound)
print("Upper bound:", upper_bound)
print("Number of outliers:", len(outliers))

Lower bound: 148.25499999999988
Upper bound: 2852.9350000000004
Number of outliers: 326

In [14]:
outliers["avg_order_value"].describe()

count     326.000000
mean     3007.210061
std       147.313261
min      2853.000000
25%      2906.972500
50%      2961.300000
75%      3066.127500
max      3567.360000
Name: avg_order_value, dtype: float64

In [15]:
print("Potential outliers identified:", len(outliers))
print("Decision: Retain because the values are plausible customer AOV observations.")

Potential outliers identified: 326
Decision: Retain because the values are plausible customer AOV observations.

In [16]:
df_clean.groupby("discount")[
    ["age", "past_purchases", "website_visits",
     "loyalty_score", "product_interest_score"]
].mean()

,age,past_purchases,website_visits,loyalty_score,product_interest_score
discount,,,,,
0,43.892413,3.010412,8.005796,50.572737,50.795238
10,44.099277,3.009821,8.003783,50.578472,50.560488
20,43.919716,3.002533,7.996134,50.586083,50.450677

In [17]:
df_clean.corr(numeric_only=True)

,age,past_purchases,product_views,website_visits,avg_order_value,days_since_last_purchase,loyalty_score,cart_additions,email_engagement,customer_tenure,product_interest_score,previous_discount_usage,discount,purchase
age,1.000000,-0.002927,-0.001669,0.001572,-0.002529,-0.003427,0.004423,0.001679,0.002820,-0.007470,-0.003705,0.003960,0.001191,-0.002920
past_purchases,-0.002927,1.000000,0.008650,0.010075,0.002130,-0.002532,-0.001467,0.000465,-0.003976,-0.006491,-0.003093,0.002338,-0.001818,0.031296
product_views,-0.001669,0.008650,1.000000,-0.002289,-0.000533,0.005613,-0.004009,-0.002397,0.003842,0.000427,-0.006079,0.004687,-0.002464,-0.004084
website_visits,0.001572,0.010075,-0.002289,1.000000,0.002051,0.002620,-0.001953,0.002296,0.003629,-0.002444,0.003451,-0.003488,-0.001380,0.013451
avg_order_value,-0.002529,0.002130,-0.000533,0.002051,1.000000,0.001050,-0.003542,-0.004453,-0.002979,0.000733,-0.000544,0.001056,-0.002044,0.002595
days_since_last_purchase,-0.003427,-0.002532,0.005613,0.002620,0.001050,1.000000,-0.000151,0.000880,-0.004076,-0.000543,-0.000150,0.000516,-0.001311,-0.070506
loyalty_score,0.004423,-0.001467,-0.004009,-0.001953,-0.003542,-0.000151,1.000000,-0.001305,0.002735,0.000361,-0.007171,-0.002108,0.000191,0.346898
cart_additions,0.001679,0.000465,-0.002397,0.002296,-0.004453,0.000880,-0.001305,1.000000,0.001154,-0.001086,0.001534,-0.004507,-0.000790,0.021002
email_engagement,0.002820,-0.003976,0.003842,0.003629,-0.002979,-0.004076,0.002735,0.001154,1.000000,0.001166,-0.000275,-0.000601,0.002027,0.001998
customer_tenure,-0.007470,-0.006491,0.000427,-0.002444,0.000733,-0.000543,0.000361,-0.001086,0.001166,1.000000,0.003068,-0.005626,-0.002621,0.001207
product_interest_score,-0.003705,-0.003093,-0.006079,0.003451,-0.000544,-0.000150,-0.007171,0.001534,-0.000275,0.003068,1.000000,0.006063,-0.005026,0.490834
previous_discount_usage,0.003960,0.002338,0.004687,-0.003488,0.001056,0.000516,-0.002108,-0.004507,-0.000601,-0.005626,0.006063,1.000000,0.001944,0.000739
discount,0.001191,-0.001818,-0.002464,-0.001380,-0.002044,-0.001311,0.000191,-0.000790,0.002027,-0.002621,-0.005026,0.001944,1.000000,0.190090
purchase,-0.002920,0.031296,-0.004084,0.013451,0.002595,-0.070506,0.346898,0.021002,0.001998,0.001207,0.490834,0.000739,0.190090,1.000000

In [18]:
df_clean["discount"].value_counts(normalize=True).sort_index()

discount
0     0.39856
10    0.30138
20    0.30006
Name: proportion, dtype: float64

In [19]:
df_clean.groupby("discount")["purchase"].agg(
    ["count", "mean", "sum"]
)

          count      mean    sum
discount
0         39856  0.433862  17292
10        30138  0.569580  17166
20        30006  0.660101  19807

In [20]:
features = [
    "age",
    "past_purchases",
    "product_views",
    "website_visits",
    "avg_order_value",
    "days_since_last_purchase",
    "loyalty_score",
    "cart_additions",
    "email_engagement",
    "customer_tenure",
    "product_interest_score",
    "previous_discount_usage"
]

X = df_clean[features]
T = df_clean["discount"]
Y = df_clean["purchase"]

In [21]:
print("X shape:", X.shape)
print("T shape:", T.shape)
print("Y shape:", Y.shape)

X shape: (100000, 12)
T shape: (100000,)
Y shape: (100000,)